Donkey_Ear/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    root 'pages#index'
  end
  authenticated :user do
    root to: "userhome#index", as: "userhome"
  end

  resources :users, except: [:new, :create] do
    member do 
      get 'followers'
      get 'following'
    end
  end

  resources :chats do
    member do
      get 'get_messages'
    end
  end
  resources :messages
  resources :comments

  resources :tweets
  resources :find_users, only: :index
  resources :relationships, only: [:create, :destroy]

end

Donkey_Ear/app/models/anonymous_profile.rb
class AnonymousProfile < ActiveRecord::Base
  belongs_to :user
end

Donkey_Ear/app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user1, :class_name => 'User', :foreign_key => 'user1_id'
  belongs_to :user2, :class_name => 'User', :foreign_key => 'user2_id'

  has_many :messages
end

Donkey_Ear/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
end

Donkey_Ear/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat
  belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
  belongs_to :receiptor, :class_name => 'User', :foreign_key => 'receiptor_id'

  def json_api
    {
      id: id,
      creator_id: creator.id,
      creator_name: creator.name,
      creator_img: creator.picture.url,
      content: content
    }
  end
end

Donkey_Ear/app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'
  belongs_to :follower, :class_name => 'User', :foreign_key => 'follower_id'
end

Donkey_Ear/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

Donkey_Ear/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :trackable, :validatable

  has_many :tweets
  has_many :followed_relationship, class_name: "Relationship", foreign_key: "user_id"
  has_many :following_relationship, class_name: "Relationship", foreign_key: "follower_id"

  has_many :chats_as_creator, class_name: "Chat", foreign_key: "user1_id"
  has_many :chats_as_participant, class_name: "Chat", foreign_key: "user2_id"

  has_many :following, through: :following_relationship, source: :user
  has_many :followed, through: :followed_relationship, source: :follower

  has_many :messages_as_creator, class_name: "Message", foreign_key: "creator_id"
  has_many :messages_as_receiptor, class_name: "Message", foreign_key: "receiptor_id"

  has_one :anonymous_profile
  mount_uploader :picture, PictureUploader
end

Donkey_Ear/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
	end
end

Donkey_Ear/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Chat.where("user1_id = ? OR user2_id = ?", current_user.id, current_user.id)
    redirect_to chat_path(@chats.last)
  end

  def show
    set_chat
    @chats = Chat.where("user1_id = ? OR user2_id = ?", current_user.id, current_user.id)
    @messages = @chat.messages
  end

  def new
    @participant = User.find(params[:participant_id])
    @chat = Chat.create(user1: current_user, user2: @participant)
    redirect_to chat_path(@chat)
  end

  def get_messages
    set_chat
    @messages = @chat.messages
    respond_to do |format|
      format.json { render json: @messages.map{|x| x.json_api} }
    end
  end

  private
  def set_chat
    @chat = Chat.find(params[:id])
  end
end

Donkey_Ear/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params) do |comment|
      comment.user = current_user
      tweet = Tweet.find(params[:tweet_id])
      comment.tweet = tweet
    end
    respond_to do |format|
      format.js
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

Donkey_Ear/app/controllers/find_users_controller.rb
class FindUsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.where("name = ?", params[:search_name])
  end
end

Donkey_Ear/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params) do |message|
      message.creator = current_user
      chat = Chat.find(params[:chat_id])
      if chat.user1 == current_user
        message.receiptor = chat.user2
      else
        message.receiptor = chat.user1
      end
      message.chat = chat
    end
    respond_to do |format|
      format.js
    end
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end
end

Donkey_Ear/app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

Donkey_Ear/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include UsersHelper
	before_action :authenticate_user!
	def create
		@tweet = Tweet.new(tweet_params) do |tweet|
			tweet.user = current_user
      
      if tweet.isAnonymous
        @anonymous_profile = tweet.user.anonymous_profile
        unless @anonymous_profile
          anonymous_name = get_anonymous_name(current_user.id)
          anonymous_picture_url = get_anonymous_picture_url(current_user.id)
          @anonymous_profile = AnonymousProfile.create({:user => current_user, :name => anonymous_name, :picture => anonymous_picture_url})
        end
      end

		end
    respond_to do |format|
	    format.js
	  end
	end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet_id = params[:id]
    respond_to do |format|
      format.js
    end
  end


  private
  def tweet_params
    params.require(:tweet).permit(:content, :isAnonymous)
  end
end

Donkey_Ear/app/controllers/userhome_controller.rb
class UserhomeController < ApplicationController
	before_action :authenticate_user!
  before_action :set_user
	def index
      @following_users_ids = current_user.following_ids
    	@tweets = Tweet.where("user_id = ? OR user_id in (?)", current_user, @following_users_ids).order('created_at DESC')
  end

  private
  def set_user
    @user = current_user
  end
end

Donkey_Ear/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  def update
    current_user.update(user_params)
    current_user.save!
    redirect_to root_path
  end

  def show
    @tweets = @user.tweets
  end

  def following
    @following = @user.following
  end

  def followers
    @followers = @user.followed
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :email, :picture)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

Donkey_Ear/app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
  		content_for(:header) { text.to_s }
	end
end

Donkey_Ear/app/helpers/chats_helper.rb
module ChatsHelper
  def find_user(user_id)
    User.find(user_id)
  end
end

Donkey_Ear/app/helpers/pages_helper.rb
module PagesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

Donkey_Ear/app/helpers/users_helper.rb
module UsersHelper
  ANONYMOUS_NAME = ["apple", "banana", "blueberry", "grape", "kiwi", "melon", "orange", "papaya", "peach", "pear"]
  def following?(user)
    !current_user.following_relationship.find_by_user_id(user.id).nil?
  end

  def get_anonymous_name(user_id)
    base_name =  ANONYMOUS_NAME[user_id % ANONYMOUS_NAME.size]
    postfix = (user_id / ANONYMOUS_NAME.size).to_s
    anonymous_name = base_name + postfix
    return anonymous_name
  end

  def get_anonymous_picture_url(user_id)
    base_name = ANONYMOUS_NAME[user_id % ANONYMOUS_NAME.size]
    return "/assets/" + base_name + ".png"
  end

  def has_chat?(user)
    !current_user.chats_as_creator.find_by_user2_id(user.id).nil? || !current_user.chats_as_participant.find_by_user1_id(user.id).nil?
  end

  def get_chat(user)
    current_user.chats_as_creator.find_by_user2_id(user.id) || current_user.chats_as_participant.find_by_user1_id(user.id)
  end
end

Donkey_Ear/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonkeyEar</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'partials/header' %>
    <div id="bg-img" data-img="/assets/background.png"></div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

Donkey_Ear/app/views/pages/index.html.erb
<div class="row", id="static-page">
  <div class="col-lg-10 col-lg-offset-1">
    <div class="row">
      <div class="col-lg-3">
        <div class="row">
          <div class="well">
            <%= render "devise/sessions/form" %>
            <%= link_to "Forgot your password?", new_password_path(:user) %>
          </div>
        </div>
        <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Create an Account</h3>
            </div>
            <div class="panel-body">
              <%= render "devise/registrations/form" %>
            </div>
          </div>
        </div>
      </div>
      <div id="landing-content" class="col-lg-9">
        <h3><b>Donkey Ear,</b></h3>
        <p>
          A social networking application built on Ruby on Rails.
        </p>
      </div>
    </div>
  </div>
</div>

Donkey_Ear/app/views/partials/_anonymous_picture.html.erb
<%= image_tag anonymous_profile.picture, class: klass %>

Donkey_Ear/app/views/partials/_follow.html.erb
<% if following?(user) %>
  <%= button_to "Unfollow", relationship_path(current_user.following_relationship.find_by_user_id(user)), method: :delete, remote: true, class: 'btn btn-success' %>
<% else %>
  <%= button_to "Follow", relationships_path(followee_id: user.id), method: :post, remote: true, class: 'btn btn-primary' %>
<% end %>

Donkey_Ear/app/views/partials/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Donkey Ear", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= form_tag(find_users_path, method: :get, id: "search-form", class: "navbar-form navbar-left") do %>
            <%= text_field_tag('search_name', nil, placeholder: "Search User", class: "search-content")  %>
            <%= submit_tag "Search", id: "search-button", class: "btn btn-primary" %>
          <% end %>

          <%= link_to chats_path(), method: :get, class: "navbar-form navbar-left" do %>
            <i class="fa fa-wechat" id="wechat-button"></i>
          <% end %>
    
          <li>
            <a href="#", class="profile-image dropdown-toggle" data-toggle="dropdown", role="button", aria-expanded="false">
              <%= image_tag current_user.picture, class: "picture-xs" %>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "#{current_user.name}<br><b>@#{current_user.name}</b>".html_safe, user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

Donkey_Ear/app/views/partials/_new_comment.html.erb
<%= form_tag comments_path(tweet_id: tweet_id), multipart: true, method: :post, remote: true do %>
  <div class="form-group">
    <div class="col-lg-11" id="comment-input-area">
      <%= text_area_tag "comment[content]", nil, id: "comment-content-" + tweet_id.to_s, class: "form-control", placeholder: "Enter Comment" %>
    </div>
    <div class="col-lg-1" id="send-comment-button">
      <%= button_tag id: "send-comment", class: "btn btn-primary pull-right" do %>
        <%= fa_icon "paper-plane" %>
      <% end %>
    </div>
  </div>
<% end %>

Donkey_Ear/app/views/partials/_new_message.html.erb
<%= form_tag messages_path(chat_id: chat_id), multipart: true, method: :post, remote: true do %>
  <div class="form-group">
    <div class="col-lg-10">
      <%= text_area_tag "message[content]", nil, class: "form-control", placeholder: "Enter Message" %>
    </div>
    <div class="col-lg-2">
      <%= button_tag id: "send-message", class: "btn btn-primary pull-right" do %>
        <%= fa_icon "paper-plane" %> Send
      <% end %>
    </div>
  </div>
<% end %>

Donkey_Ear/app/views/partials/_new_tweet.html.erb
<%= form_tag tweets_path(parent_id: tweet_id), multipart: true, method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag "tweet[content]", nil, class: "form-control", placeholder: "Enter Feed" %>
  </div>
  <div class="form-group hidden">
    <img id="tweet-img-preview">
    <a id="remove-tweet-img" href="#">&times;</a>
  </div>
  <div class="form-group">
    <%= button_tag id: "tweet", class: "btn btn-primary" do %>
      <%= fa_icon "paper-plane" %> Tweet
    <% end %>
    <%= check_box_tag "tweet[isAnonymous]" %>
    <%= label_tag(:isAnonymous, "Post Anonymously") %>
  </div>
<% end %>

Donkey_Ear/app/views/partials/_picture.html.erb
<%= link_to user_path(user) do %>
  <%= image_tag user.picture.url, class: klass %>
<% end %>

Donkey_Ear/app/views/partials/_startchat.html.erb
<% if has_chat?(user) %>
  <%= button_to "Chat", chat_path(get_chat(user)), method: :get, class: 'btn btn-success' %>
<% else %>
  <%= link_to "Chat", new_chat_path(:participant_id => user.id), class: 'btn btn-success' %>
<% end %>

Donkey_Ear/app/views/partials/_user_card.html.erb
<div class="card">
  <div class="cover" id="cover" data-cover="<%= user.picture %>">
  </div>
  <div class="about">
    <h3 class="name"><%= user.name %></h3>
    <% if view_type == 'profile' %>
      <div class="row">
        <% unless @user.location.blank? %>
          <h5><i class="fa fa-map-marker"></i> <%= @user.location %></h5>
        <% end %>
        <% unless @user.website.blank? %>
          <h5><i class="fa fa-link"></i> <%= link_to @user.website, @user.website %></h5>
        <% end %>
        <h5><i class="fa fa-clock-o"></i> Joined <%= formatted_time(@user.created_at) %></h5>
      </div>
    <% else %>
      <div class="stats">
        <div class="row">
          <div class="col-lg-4 text-center">
            <%= link_to user_path(user) do %>
              <h5><b>Tweets</b></h5>
              <h4 id="tweets-count"><%= @user.tweets.count %></h4>
            <% end %>
          </div>
          <div class="col-lg-4 text-center">
            <%= link_to followers_user_path(user) do %>
              <h5><b>Followers</b></h5>
              <h4 id="followers-count"><%= @user.followed.count %></h4>
            <% end %>
          </div>
          <div class="col-lg-4 text-center">
            <%= link_to following_user_path(user) do %>
              <h5><b>Following</b></h5>
              <h4 id="following-count"><%= @user.following.count %></h4>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>