Donkey_Ear/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    root 'pages#index'
  end
  authenticated :user do
    root to: "userhome#index", as: "userhome"
  end

  resources :users, except: [:new, :create] do
    member do 
      get 'followers'
      get 'following'
    end
  end

  resources :chats do
    member do
      get 'get_messages'
    end
  end
  resources :messages
  resources :comments

  resources :tweets
  resources :find_users, only: :index
  resources :relationships, only: [:create, :destroy]

end

Donkey_Ear/app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user1, :class_name => 'User', :foreign_key => 'user1_id'
  belongs_to :user2, :class_name => 'User', :foreign_key => 'user2_id'

  has_many :messages
end

Donkey_Ear/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Chat.where("user1_id = ? OR user2_id = ?", current_user.id, current_user.id)
    redirect_to chat_path(@chats.last)
  end

  def show
    set_chat
    @chats = Chat.where("user1_id = ? OR user2_id = ?", current_user.id, current_user.id)
    @messages = @chat.messages
  end

  def new
    @participant = User.find(params[:participant_id])
    @chat = Chat.create(user1: current_user, user2: @participant)
    redirect_to chat_path(@chat)
  end

  def get_messages
    set_chat
    @messages = @chat.messages
    respond_to do |format|
      format.json { render json: @messages.map{|x| x.json_api} }
    end
  end

  private
  def set_chat
    @chat = Chat.find(params[:id])
  end
end

Donkey_Ear/app/helpers/chats_helper.rb
module ChatsHelper
  def find_user(user_id)
    User.find(user_id)
  end
end

Donkey_Ear/app/views/chats/_chat.html.erb
<% if chat.id == @chat.id %>
  <div class="row" id="chat" style="background-color: #F0F8FF;">
<% else %>
  <div class="row" id="chat">
<% end %>
  <%= link_to chat_path(chat) do %>
    <div class="col-lg-3">
      <% if chat.user1 == current_user %>
        <%= image_tag chat.user2.picture.url, class: 'picture-md' %>
      <% else %>
        <%= image_tag chat.user1.picture.url, class: 'picture-md' %>
      <% end %> 
    </div>
    <div class="col-lg-7">
      <% if chat.user1 == current_user %>
        <h5><%= chat.user2.name %></h5>
      <% else %>
        <h5><%= chat.user1.name %></h5>
      <% end %> 
    </div>
  <% end %>
  </br>
  </br>
  </br>
</div>

Donkey_Ear/app/views/chats/show.html.erb
<div class="row">
  <div class="col-lg-3" id="chat-lists">
    <%= render(@chats) || "No Chats" %>
  </div>
  <div class="col-lg-6">
    <div id="content">
      <div id="message" class="well message">
        <%= render(@messages) || "No Messages" %>
      </div>
    </div>
    <div id="new-message">
      <%= render 'partials/new_message', chat_id: @chat.id%>
    </div>
  </div>
  <div class="col-lg-3">
  </div>
</div>


<script>
  function new_message(data) {
    function get_pic_html() {
      var img_url = "";
      if (data.creator_img) {
        img_url = data.creator_img;
      } else {
        img_url = '/assets/default_user.png';
      }
      if (data.creator_id != "<%= current_user.id%>") {
        return "<div class = 'picture-content'>" + "<img class = 'picture' " + "src ='" + img_url  + "' alt = 'Background'>" + "</div>";
      } else {
        return "<div class = 'picture-content pull-right'>" + "<img class = 'picture' " + "src ='" + img_url + "' alt = 'Background'>" + "</div>";
      }
    }

    function get_content_html() {
      if (data.creator_id != "<%= current_user.id%>") {
        return "<div class = 'post-content'>" + "<div class = 'post'>" + data.content + "</div>" + "</div>";
      } else {
        return "<div class = 'post-content' style = 'width: 90%;'>" + "<div class = 'post pull-right'>" + data.content + "</div>" + "</div>";
      }
    }

    function get_header_html() {
      return "<div id = 'message-" + data.id + "'" + " class='micropost'>" + 
        "<div class = 'content'>";
    }

    function get_tail_html() {
      return "</div>" + "</div>";
    }

    var new_message = "";
    if (data.creator_id != "<%= current_user.id%>") {
      new_message =  get_header_html() + get_pic_html() + get_content_html()
         + get_tail_html();
    } else {
      new_message = get_header_html() + get_content_html() + get_pic_html() + get_tail_html();
    }
    return new_message;
  }

  const url_for_messages = "<%= get_messages_chat_path() %>";
  function ajax_call() {
    const url_for_messages = "<%= get_messages_chat_path() %>";
    $.ajax({
         method: 'GET',
         url: url_for_messages,
         dataType: 'json'
      })
         .done(function(data){
            var html = '';
             
            data.forEach(function(message_new){
               html += new_message(message_new);
            });
             
            $('#message').html(html);
         });
  }

  ajax_call();
  $(function() {
    const url_for_messages = "<%= get_messages_chat_path() %>";
    setInterval(function(){
      ajax_call();
    }, 0.1 * 1000);
  });
</script>