Donkey_Ear/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    root 'pages#index'
  end
  authenticated :user do
    root to: "userhome#index", as: "userhome"
  end

  resources :users, except: [:new, :create] do
    member do 
      get 'followers'
      get 'following'
    end
  end

  resources :chats do
    member do
      get 'get_messages'
    end
  end
  resources :messages
  resources :comments

  resources :tweets
  resources :find_users, only: :index
  resources :relationships, only: [:create, :destroy]

end

Donkey_Ear/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

Donkey_Ear/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include UsersHelper
	before_action :authenticate_user!
	def create
		@tweet = Tweet.new(tweet_params) do |tweet|
			tweet.user = current_user
      
      if tweet.isAnonymous
        @anonymous_profile = tweet.user.anonymous_profile
        unless @anonymous_profile
          anonymous_name = get_anonymous_name(current_user.id)
          anonymous_picture_url = get_anonymous_picture_url(current_user.id)
          @anonymous_profile = AnonymousProfile.create({:user => current_user, :name => anonymous_name, :picture => anonymous_picture_url})
        end
      end

		end
    respond_to do |format|
	    format.js
	  end
	end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet_id = params[:id]
    respond_to do |format|
      format.js
    end
  end


  private
  def tweet_params
    params.require(:tweet).permit(:content, :isAnonymous)
  end
end

Donkey_Ear/app/views/tweets/_tweet.html.erb
<div id="tweet-<%= tweet.id %>" class="micropost">
  <div class="content">
    <div class="picture-content">
      <% if tweet.isAnonymous %>
        <%= render 'partials/anonymous_picture', anonymous_profile: tweet.user.anonymous_profile, klass: 'picture' %>
      <% else %>
        <%= link_to tweet.user do %>
          <%= render 'partials/picture', user: tweet.user, klass: 'picture' %>
        <% end %>
      <% end %>
    </div>
    <div class="post-content">
      <% if tweet.isAnonymous %>
        <span class="name"><%= tweet.user.anonymous_profile.name %></span>
      <% else %>
        <%= link_to tweet.user do %>
          <span class="name"><%= tweet.user.name %></span>
        <% end %>
      <% end %>
      <div class="post">
        <%= tweet.content %>
      </div>
      <div class="media">
        
      </div>
    </div>
    <div class="right-content">
      <span><%= time_ago_in_words(tweet.created_at) %></span>
    </div>
  </div>
  <div class="actions">
    <div class="actions-content">
      <a id="comment-btn-<%= tweet.id %>" href="#">
        <i class="fa fa-comment"></i>
        <script type="text/javascript">
          $(function() {
            $('#comment-btn-<%= tweet.id %>').click(function() {
              $('#comments-<%=tweet.id %>').append("Comments")
              $('#comments-<%=tweet.id %>').append("<%=j render(tweet.comments) %>");
              $('#commenting-<%= tweet.id %>').append("<%=j render('partials/new_comment', tweet_id: tweet.id) %>");
            });
          });
        </script>
      </a>
      <% if tweet.user == current_user %>
        <%= link_to tweet_path(tweet), method: :delete, remote: true do %>
          <i class="fa fa-trash"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="comments" id="comments-<%= tweet.id %>">
  </div>
  <div class="commenting" id="commenting-<%= tweet.id %>">
  </div>
</div>

Donkey_Ear/app/views/tweets/create.js.erb
<% if @tweet.save %>
	$("#tweet_content").val("");
	$("#feed").prepend("<%=j render @tweet %>");
  $("#tweets-count").html("<%= current_user.tweets.count %>");
<% end %>

Donkey_Ear/app/views/tweets/destroy.js.erb
<% if @tweet.destroy %>
  $("#tweet-<%= @tweet_id %>").remove();
  $("#tweets-count").html("<%= current_user.tweets.count %>");
<% end %>